name: Git builds

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Only trigger manually
on: workflow_dispatch

jobs:
  shutorial-regular-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: prepare for Debian
        run: |
          sudo apt install debhelper-compat python3 python3-markdown python3-markupsafe python3-jinja2 sharutils
          cp -r distros/debian .
          make debian
          mkdir dist
          mv shutorial_*_all.deb dist
      -
        name: upload
        uses: actions/upload-artifact@v3
        with:
          path: dist/shutorial_*_all.deb
          name: debian_package
